import os
import sys
import json
from datetime import datetime

sys.path.insert(0, '/app')
from dotenv import load_dotenv
load_dotenv()


def get_client():
    """
    Creates Azure DevOps connection.
    Uses PAT token from .env
    """
    from azure.devops.connection import Connection
    from msrest.authentication import BasicAuthentication

    pat = os.getenv("AZURE_PAT")
    org_url = os.getenv("AZURE_ORG_URL")

    if not pat or not org_url:
        raise ValueError(
            "AZURE_PAT and AZURE_ORG_URL required in .env"
        )

    credentials = BasicAuthentication('', pat)
    connection = Connection(base_url=org_url,
                           creds=credentials)
    return connection

def upload_attachment(image_path: str,
                      wit_client) -> str:
    """
    Uploads an image to Azure DevOps as an attachment.
    Returns the attachment URL to embed in work item.
    """
    import mimetypes

    if not image_path or not os.path.exists(image_path):
        return None

    print(f"  📎 Uploading screenshot as attachment...")

    filename = os.path.basename(image_path)
    mime_type = mimetypes.guess_type(image_path)[0] or 'image/jpeg'

    with open(image_path, 'rb') as f:
        upload_stream = f

        attachment = wit_client.create_attachment(
            upload_stream=upload_stream,
            file_name=filename,
            upload_type='Simple',
            project=os.getenv("AZURE_PROJECT")
        )

    print(f"  ✅ Screenshot uploaded: {attachment.url}")
    return attachment.url

def format_ticket_with_claude(finding: dict,
                               user_story: str) -> dict:
    """
    Uses Claude to format a perfect Azure DevOps
    work item from a design finding.

    Returns:
        dict: {
            title, description, priority,
            tags, effort_estimate
        }
    """
    import anthropic

    client = anthropic.Anthropic(
        api_key=os.getenv("ANTHROPIC_API_KEY")
    )

    prompt = f"""You are a Senior QA Engineer creating
an Azure DevOps work item from a design verification finding.

FINDING:
Type: {finding['type']}
Element: {finding['element']}
Screen: {finding.get('screen_reference', 'N/A')}
Requirement: {finding.get('requirement_reference', 'N/A')}
Description: {finding['description']}
Risk: {finding.get('risk_level', 'MEDIUM')}
Action: {finding.get('recommended_action', '')}

USER STORY:
{user_story[:500]}

Create a professional Azure DevOps work item.
Respond ONLY with valid JSON:

{{
  "title": "concise title under 80 chars",
  "description": "full HTML description with sections",
  "priority": 1,
  "tags": ["clarity-auto", "design-mismatch"],
  "effort_hours": 2,
  "acceptance_criteria": "Given/When/Then for the fix"
}}

Priority rules:
  HIGH risk   → priority 1
  MEDIUM risk → priority 2
  LOW risk    → priority 3

For description use HTML format with these sections:
  <h3>🤖 Generated by Clarity AI</h3>
  <h3>Finding Details</h3>
  <h3>Requirement</h3>
  <h3>Acceptance Criteria for Fix</h3>
  <h3>Effort Estimate</h3>

Respond ONLY with JSON. No markdown."""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}]
    )

    response = message.content[0].text.strip()
    if response.startswith("```"):
        response = response.split("```")[1]
        if response.startswith("json"):
            response = response[4:]

    clean = response.strip()

    try:
        return json.loads(clean, strict=False)
    except json.JSONDecodeError:
        # Claude returned malformed JSON — use safe fallback
        print(f"  ⚠️  Claude JSON malformed — using fallback")
        return {
            "title": f"{finding['type']}: {finding['element'][:60]}",
            "description": finding['description'],
            "priority": 1 if finding.get('risk_level') == 'HIGH' else 2,
            "tags": ["clarity-auto", "design-mismatch"],
            "effort_hours": 2,
            "acceptance_criteria": finding.get(
                'recommended_action', 'Fix the design mismatch'
            )
        }


def create_work_item(finding: dict,
                     user_story: str,
                     sprint_name: str = None,
                     image_path: str = None) -> dict:
    """
    Creates a single Azure DevOps work item
    from a design finding.

    Improvements:
    1. Screenshot attached to Repro Steps
    2. Better AC format
    3. Auto-assigned to designer

    Args:
        finding:     single finding from design_verifier
        user_story:  the requirement being verified
        sprint_name: "Sprint 1" etc (optional)
        image_path:  path to the Figma screenshot (optional)

    Returns:
        dict: { id, url, title, status }
    """

    project = os.getenv("AZURE_PROJECT")
    work_item_type = os.getenv(
        "AZURE_WORK_ITEM_TYPE", "Bug"
    )
    designer_email = os.getenv("AZURE_DESIGNER_EMAIL", "")

    print(f"\n  📝 Formatting ticket with Claude...")
    ticket = format_ticket_with_claude(finding, user_story)

    print(f"  🔗 Creating in Azure DevOps...")
    print(f"     Title: {ticket['title'][:60]}...")

    connection = get_client()
    wit_client = connection.clients.get_work_item_tracking_client()

    from azure.devops.v7_1.work_item_tracking.models import (
        JsonPatchOperation
    )

    risk_icon = {
        "HIGH":   "🔴",
        "MEDIUM": "🟡",
        "LOW":    "🟢"
    }.get(finding.get('risk_level', 'MEDIUM'), '⚪')

    # ── Upload image as attachment ─────────────────────────
    image_html = ""
    attachment_url = None

    if image_path and os.path.exists(image_path):
        try:
            attachment_url = upload_attachment(
                image_path, wit_client
            )
            if attachment_url:
                image_html = f"""
<h4>📸 Design Screenshot (evidence)</h4>
<img src="{attachment_url}"
     style="max-width:600px; border:1px solid #ccc;
            border-radius:4px; margin:10px 0;"
     alt="Design screenshot showing the issue"/>
<p><i>Screenshot uploaded by Clarity Design Verifier</i></p>
"""
        except Exception as e:
            print(f"  ⚠️  Screenshot upload failed: {e}")
            image_html = f"""
<h4>📸 Design Screenshot</h4>
<p>Screenshot: {os.path.basename(image_path)}</p>
<p><i>Attach manually from your Clarity project folder</i></p>
"""

    repro_steps = f"""
<h3>🔍 Finding Details</h3>
<table border="1" cellpadding="6" cellspacing="0"
       style="border-collapse:collapse; width:100%">
  <tr style="background:#f5f5f5">
    <td><b>Finding Type</b></td>
    <td><b>{finding['type']}</b></td>
  </tr>
  <tr>
    <td><b>Risk Level</b></td>
    <td>{risk_icon} {finding.get('risk_level','')}</td>
  </tr>
  <tr style="background:#f5f5f5">
    <td><b>Element</b></td>
    <td>{finding['element']}</td>
  </tr>
  <tr>
    <td><b>Screen</b></td>
    <td>{finding.get('screen_reference','N/A')}</td>
  </tr>
  <tr style="background:#f5f5f5">
    <td><b>Requirement</b></td>
    <td>{finding.get('requirement_reference','N/A')}</td>
  </tr>
</table>

<h3>📋 Description</h3>
<p>{finding['description']}</p>

<h3>✅ Required Action</h3>
<p>{finding.get('recommended_action','')}</p>

{image_html}

<h3>📊 Clarity Metadata</h3>
<table border="1" cellpadding="6" cellspacing="0"
       style="border-collapse:collapse; width:100%">
  <tr style="background:#f5f5f5">
    <td><b>Generated by</b></td>
    <td>Clarity AI v1.0</td>
  </tr>
  <tr>
    <td><b>Date</b></td>
    <td>{datetime.now().strftime('%Y-%m-%d %H:%M')}</td>
  </tr>
  <tr style="background:#f5f5f5">
    <td><b>Prevents Bug</b></td>
    <td>{'Yes ✅' if finding.get('prevents_bug') else 'No'}</td>
  </tr>
</table>
"""

    # ── Build Acceptance Criteria ──────────────────────────
    ac_raw = ticket.get('acceptance_criteria', '')

    # Format as numbered list if Claude returned plain text
    ac_lines = [
        line.strip()
        for line in ac_raw.split('\n')
        if line.strip()
    ]

    ac_html = "<h3>Acceptance Criteria</h3><ol>"
    for line in ac_lines:
        # Highlight Given/When/Then
        line = line.replace('Given ', '<b>Given</b> ')
        line = line.replace('When ',  '<b>When</b> ')
        line = line.replace('Then ',  '<b>Then</b> ')
        ac_html += f"<li>{line}</li>"
    ac_html += "</ol>"

    ac_html += f"""
<h3>Definition of Done</h3>
<ul>
  <li>Designer has updated Figma to address this finding</li>
  <li>PM has re-run Clarity Design Verification</li>
  <li>Alignment score improved for this element</li>
  <li>Finding type changed to MATCH in next verification</li>
</ul>
"""

    # ── Build patch document ───────────────────────────────
    patch_document = [
        JsonPatchOperation(
            op="add",
            path="/fields/System.Title",
            value=f"[CLARITY] {ticket['title']}"
        ),
        JsonPatchOperation(
            op="add",
            path="/fields/Microsoft.VSTS.TCM.ReproSteps",
            value=repro_steps
        ),
        JsonPatchOperation(
            op="add",
            path="/fields/Microsoft.VSTS.Common.AcceptanceCriteria",
            value=ac_html
        ),
        JsonPatchOperation(
            op="add",
            path="/fields/Microsoft.VSTS.Common.Priority",
            value=ticket.get('priority', 2)
        ),
        JsonPatchOperation(
            op="add",
            path="/fields/System.Tags",
            value="; ".join(
                ticket.get('tags', ['clarity-auto'])
            )
        ),
    ]

    # ── Auto-assign to designer ────────────────────────────
    if designer_email:
        patch_document.append(
            JsonPatchOperation(
                op="add",
                path="/fields/System.AssignedTo",
                value=designer_email
            )
        )
        print(f"     Assigned to: {designer_email}")

    # ── Add sprint ─────────────────────────────────────────
    if sprint_name:
        patch_document.append(
            JsonPatchOperation(
                op="add",
                path="/fields/System.IterationPath",
                value=f"{project}\\{sprint_name}"
            )
        )

    # ── Link attachment to work item ───────────────────────
    if attachment_url:
        patch_document.append(
            JsonPatchOperation(
                op="add",
                path="/relations/-",
                value={
                    "rel": "AttachedFile",
                    "url": attachment_url,
                    "attributes": {
                        "comment": "Design screenshot — Clarity AI evidence"
                    }
                }
            )
        )

    # ── Create the work item ───────────────────────────────
    work_item = wit_client.create_work_item(
        document=patch_document,
        project=project,
        type=work_item_type
    )

    org_url = os.getenv("AZURE_ORG_URL")
    item_url = (
        f"{org_url}/{project}/_workitems/edit/{work_item.id}"
    )

    print(f"  ✅ Work item created!")
    print(f"     ID:  {work_item.id}")
    print(f"     URL: {item_url}")

    return {
        "id": work_item.id,
        "url": item_url,
        "title": f"[CLARITY] {ticket['title']}",
        "status": "created",
        "finding_type": finding['type'],
        "risk_level": finding.get('risk_level', 'MEDIUM'),
        "assigned_to": designer_email
    }


def create_tickets_from_verification(
    verification_result: dict,
    user_story: str,
    sprint_name: str = None,
    risk_threshold: str = "MEDIUM",
    image_path: str = None
) -> list:
    """
    Creates Azure DevOps tickets for ALL findings
    above the risk threshold.

    Args:
        verification_result: output from design_verifier
        user_story:          the requirement verified
        sprint_name:         "Sprint 1" etc
        risk_threshold:      "HIGH" = only high risk
                             "MEDIUM" = high + medium
                             "LOW" = all findings

    Returns:
        list of created ticket details
    """

    risk_levels = {
        "HIGH":   ["HIGH"],
        "MEDIUM": ["HIGH", "MEDIUM"],
        "LOW":    ["HIGH", "MEDIUM", "LOW"]
    }

    allowed_risks = risk_levels.get(
        risk_threshold, ["HIGH", "MEDIUM"]
    )

    # Only create tickets for non-matching findings
    actionable_types = ["MISSING", "EXTRA", "MISMATCH"]

    findings_to_ticket = [
        f for f in verification_result['findings']
        if f['type'] in actionable_types
        and f.get('risk_level', 'LOW') in allowed_risks
    ]

    print(f"\n{'='*60}")
    print(f"  CLARITY — Azure DevOps Integration")
    print(f"{'='*60}")
    print(f"\n  Project:   {os.getenv('AZURE_PROJECT')}")
    print(f"  Sprint:    {sprint_name or 'No sprint assigned'}")
    print(f"  Threshold: {risk_threshold} and above")
    print(f"  Findings:  {len(findings_to_ticket)} tickets to create")
    print(f"  (Skipping {len(verification_result['findings']) - len(findings_to_ticket)} MATCH/LOW findings)")

    created_tickets = []

    for i, finding in enumerate(findings_to_ticket):
        print(f"\n  [{i+1}/{len(findings_to_ticket)}] "
              f"{finding['type']} — "
              f"{finding.get('risk_level','?')} risk")
        print(f"     {finding['element'][:50]}...")

        try:
            ticket = create_work_item(
                finding=finding,
                user_story=user_story,
                sprint_name=sprint_name,
                image_path=image_path
            )
            created_tickets.append(ticket)

        except Exception as e:
            print(f"  ❌ Failed to create ticket: {e}")
            created_tickets.append({
                "status": "failed",
                "error": str(e),
                "finding_type": finding['type'],
                "element": finding['element']
            })

    # Summary
    successful = [t for t in created_tickets
                  if t.get('status') == 'created']
    failed = [t for t in created_tickets
              if t.get('status') == 'failed']

    print(f"\n{'='*60}")
    print(f"  TICKETS CREATED: {len(successful)} ✅")
    if failed:
        print(f"  TICKETS FAILED:  {len(failed)} ❌")
    print(f"{'='*60}")

    if successful:
        print(f"\n  View in Azure DevOps:")
        org = os.getenv('AZURE_ORG_URL')
        proj = os.getenv('AZURE_PROJECT')
        print(f"  {org}/{proj}/_boards/board")

    return created_tickets


if __name__ == "__main__":

    print("\n  Testing Azure DevOps Integration")
    print("  " + "─" * 40)

    # Load the last verification result
    import os
    if not os.path.exists("verification_output.json"):
        print("\n  ❌ No verification_output.json found")
        print("  Run design_verifier.py first")
    else:
        with open("verification_output.json") as f:
            verification = json.load(f)

        user_story = """
        As a registered user, I want to log in with
        my email and password so that I can access
        my account securely.

        AC1: Given valid credentials, When I click login,
             Then I am redirected to dashboard.
        AC2: Given invalid credentials, When I click login,
             Then I see an error message.
        AC3: Given I forgot my password, When I click reset,
             Then I receive a reset email.
        AC4: Given I check remember me, When I login,
             Then my session persists for 30 days.
        """

        print(f"\n  Verification loaded:")
        print(f"  Alignment: {verification['alignment_score']}%")
        print(f"  Findings:  {len(verification['findings'])}")

        tickets = create_tickets_from_verification(
            verification_result=verification,
            user_story=user_story,
            sprint_name="Sprint 1",
            risk_threshold="MEDIUM",
            image_path="image_test.jpg"
)

        with open("tickets_output.json", "w") as f:
            json.dump(tickets, f, indent=2)

        print(f"\n  💾 Saved to tickets_output.json")